"""Clothing vocabulary - Shared pools & probabilities (loaded from JSON)."""

from ..loader import load_json

_data = load_json("clothing_constants.json")

PALETTE_DEFAULT_PROBABILITIES = _data["PALETTE_DEFAULT_PROBABILITIES"]
OPTIONAL_DETAIL_PROBABILITY = _data["OPTIONAL_DETAIL_PROBABILITY"]
STATE_DETAIL_PROBABILITY = _data["STATE_DETAIL_PROBABILITY"]
OUTERWEAR_SELECTION_PROBABILITY = _data["OUTERWEAR_SELECTION_PROBABILITY"]
EMBELLISHMENT_DETAIL_PROBABILITY = _data["EMBELLISHMENT_DETAIL_PROBABILITY"]
STATE_TAGS = _data["STATE_TAGS"]
